var runes = [
    {id:5001,tier:1,name:"Lesser Mark of Strength",description:"+0.53 attack damage",rank:"1",effect:"PHYSICAL",cost:15},
    {id:5002,tier:1,name:"Lesser Mark of Might",description:"+0.08 attack damage per level (+1.35 at champion level 18)",rank:"1",effect:"PHYSICAL",cost:30},
    {id:5003,tier:1,name:"Lesser Mark of Alacrity",description:"+0.94% attack speed",rank:"1",effect:"PHYSICAL",cost:30},
    {id:5004,tier:1,name:"Lesser Mark of Haste",description:"+0.03% attack speed per level (+0.54% at champion level 18)",rank:"1",effect:"PHYSICAL",cost:30},
    {id:5005,tier:1,name:"Lesser Mark of Furor",description:"+1.24% critical damage",rank:"1",effect:"PHYSICAL",cost:65},
    {id:5006,tier:1,name:"Lesser Mark of Carnage",description:"+0.03% critical damage per level (+0.54% at champion level 18)",rank:"1",effect:"PHYSICAL",cost:65},
    {id:5007,tier:1,name:"Lesser Mark of Malice",description:"+0.52% critical chance",rank:"1",effect:"PHYSICAL",cost:30},
    {id:5008,tier:1,name:"Lesser Mark of Brutality",description:"+0.03% critical chance per level (+0.54% at champion level 18)",rank:"1",effect:"PHYSICAL",cost:30},
    {id:5009,tier:1,name:"Lesser Mark of Desolation",description:"+0.93 armor penetration",rank:"1",effect:"PHYSICAL",cost:30},
    {id:5010,tier:1,name:"Lesser Mark of Precision",description:"+0.03 armor penetration per level (+0.54 at champion level 18)",rank:"1",effect:"PHYSICAL",cost:30},
    {id:5011,tier:1,name:"Lesser Mark of Fortitude",description:"+1.93 health",rank:"1",effect:"HEALTH",cost:30},
    {id:5012,tier:1,name:"Lesser Mark of Vitality",description:"+0.3 health per level (+5.4 at champion level 18)",rank:"1",effect:"HEALTH",cost:65},
    {id:5013,tier:1,name:"Lesser Mark of Resilience",description:"+0.51 armor",rank:"1",effect:"DEFENSE",cost:15},
    {id:5014,tier:1,name:"Lesser Mark of Defense",description:"+0.05 armor per level (+0.9 at champion level 18)",rank:"1",effect:"DEFENSE",cost:15},
    {id:5015,tier:1,name:"Lesser Mark of Warding",description:"+0.54 magic resist",rank:"1",effect:"DEFENSE",cost:15},
    {id:5016,tier:1,name:"Lesser Mark of Shielding",description:"+0.04 magic resist per level (+0.72 at champion level 18)",rank:"1",effect:"DEFENSE",cost:15},
    {id:5017,tier:1,name:"Lesser Mark of Vigor",description:"+0.15 health regen / 5 sec.",rank:"1",effect:"UTILITY",cost:65},
    {id:5018,tier:1,name:"Lesser Mark of Regeneration",description:"+0.05 health regen / 5 sec. per level (+0.9 at champion level 18)",rank:"1",effect:"UTILITY",cost:65},
    {id:5019,tier:1,name:"Lesser Mark of Evasion",description:"+0.21% dodge",rank:"1",effect:"UTILITY",cost:30},
    {id:5020,tier:1,name:"Lesser Mark of Elusion",description:"+0.01% dodge per level (+0.18% at champion level 18)",rank:"1",effect:"UTILITY",cost:30},
    {id:5021,tier:1,name:"Lesser Mark of Focus",description:"-0.09% cooldowns",rank:"1",effect:"UTILITY",cost:30},
    {id:5022,tier:1,name:"Lesser Mark of Celerity",description:"-0.01% cooldowns per level (-0.18% at champion level 18)",rank:"1",effect:"UTILITY",cost:30},
    {id:5023,tier:1,name:"Lesser Mark of Potency",description:"+0.33 ability power",rank:"1",effect:"MAGIC",cost:30},
    {id:5024,tier:1,name:"Lesser Mark of Force",description:"+0.06 ability power per level (+1.08 at champion level 18)",rank:"1",effect:"MAGIC",cost:30},
    {id:5025,tier:1,name:"Lesser Mark of Intellect",description:"+3.28 mana",rank:"1",effect:"MANA",cost:30},
    {id:5026,tier:1,name:"Lesser Mark of Knowledge",description:"+0.65 mana per level (+11.7 at champion level 18)",rank:"1",effect:"MANA",cost:30},
    {id:5027,tier:1,name:"Lesser Mark of Replenishment",description:"+0.15 mana regen / 5 sec.",rank:"1",effect:"UTILITY",cost:15},
    {id:5028,tier:1,name:"Lesser Mark of Clarity",description:"+0.04 mana regen / 5 sec. per level (+0.72 at champion level 18)",rank:"1",effect:"UTILITY",cost:15},
    {id:5029,tier:1,name:"Lesser Mark of Insight",description:"+0.53 magic penetration",rank:"1",effect:"MAGIC",cost:30},
    {id:5030,tier:1,name:"Lesser Mark of Brilliance",description:"+0.03 magic penetration per level (+0.54 at champion level 18)",rank:"1",effect:"MAGIC",cost:30},
    {id:5031,tier:1,name:"Lesser Glyph of Strength",description:"+0.16 attack damage",rank:"1",effect:"PHYSICAL",cost:15},
    {id:5032,tier:1,name:"Lesser Glyph of Might",description:"+0.02 attack damage per level (+0.36 at champion level 18)",rank:"1",effect:"PHYSICAL",cost:15},
    {id:5033,tier:1,name:"Lesser Glyph of Alacrity",description:"+0.35% attack speed",rank:"1",effect:"PHYSICAL",cost:30},
    {id:5034,tier:1,name:"Lesser Glyph of Haste",description:"+0.01% attack speed per level (+0.18% at champion level 18)",rank:"1",effect:"PHYSICAL",cost:30},
    {id:5035,tier:1,name:"Lesser Glyph of Furor",description:"+0.31% critical damage",rank:"1",effect:"PHYSICAL",cost:65},
    {id:5036,tier:1,name:"Lesser Glyph of Carnage",description:"+0.01% critical damage per level (+0.18% at champion level 18)",rank:"1",effect:"PHYSICAL",cost:65},
    {id:5037,tier:1,name:"Lesser Glyph of Malice",description:"+0.15% critical chance",rank:"1",effect:"PHYSICAL",cost:30},
    {id:5038,tier:1,name:"Lesser Glyph of Brutality",description:"+0.01% critical chance per level (+0.18% at champion level 18)",rank:"1",effect:"PHYSICAL",cost:30},
    {id:5039,tier:1,name:"Lesser Glyph of Desolation",description:"+0.22 armor penetration",rank:"1",effect:"PHYSICAL",cost:30},
    {id:5040,tier:1,name:"Lesser Glyph of Precision",description:"+0.01 armor penetration per level (+0.18 at champion level 18)",rank:"1",effect:"PHYSICAL",cost:30},
    {id:5041,tier:1,name:"Lesser Glyph of Fortitude",description:"+1.49 health",rank:"1",effect:"HEALTH",cost:30},
    {id:5042,tier:1,name:"Lesser Glyph of Vitality",description:"+0.3 health per level (+5.4 at champion level 18)",rank:"1",effect:"HEALTH",cost:65},
    {id:5043,tier:1,name:"Lesser Glyph of Resilience",description:"+0.39 armor",rank:"1",effect:"DEFENSE",cost:15},
    {id:5044,tier:1,name:"Lesser Glyph of Defense",description:"+0.05 armor per level (+0.9 at champion level 18)",rank:"1",effect:"DEFENSE",cost:15},
    {id:5045,tier:1,name:"Lesser Glyph of Warding",description:"+0.83 magic resist",rank:"1",effect:"DEFENSE",cost:15},
    {id:5046,tier:1,name:"Lesser Glyph of Shielding",description:"+0.08 magic resist per level (+1.44 at champion level 18)",rank:"1",effect:"DEFENSE",cost:15},
    {id:5047,tier:1,name:"Lesser Glyph of Vigor",description:"+0.15 health regen / 5 sec.",rank:"1",effect:"UTILITY",cost:65},
    {id:5048,tier:1,name:"Lesser Glyph of Regeneration",description:"+0.05 health regen / 5 sec. per level (+0.9 at champion level 18)",rank:"1",effect:"UTILITY",cost:65},
    {id:5049,tier:1,name:"Lesser Glyph of Evasion",description:"+0.21% dodge",rank:"1",effect:"UTILITY",cost:30},
    {id:5050,tier:1,name:"Lesser Glyph of Elusion",description:"+0.01% dodge per level (+0.18% at champion level 18)",rank:"1",effect:"UTILITY",cost:30},
    {id:5051,tier:1,name:"Lesser Glyph of Focus",description:"-0.36% cooldowns",rank:"1",effect:"UTILITY",cost:65},
    {id:5052,tier:1,name:"Lesser Glyph of Celerity",description:"-0.03% cooldowns per level (-0.54% at champion level 18)",rank:"1",effect:"UTILITY",cost:30},
    {id:5053,tier:1,name:"Lesser Glyph of Potency",description:"+0.55 ability power",rank:"1",effect:"MAGIC",cost:30},
    {id:5054,tier:1,name:"Lesser Glyph of Force",description:"+0.1 ability power per level (+1.8 at champion level 18)",rank:"1",effect:"MAGIC",cost:30},
    {id:5055,tier:1,name:"Lesser Glyph of Intellect",description:"+6.25 mana",rank:"1",effect:"MANA",cost:30},
    {id:5056,tier:1,name:"Lesser Glyph of Knowledge",description:"+0.79 mana per level (+14.22 at champion level 18)",rank:"1",effect:"MANA",cost:30},
    {id:5057,tier:1,name:"Lesser Glyph of Replenishment",description:"+0.17 mana regen / 5 sec.",rank:"1",effect:"UTILITY",cost:30},
    {id:5058,tier:1,name:"Lesser Glyph of Clarity",description:"+0.03 mana regen / 5 sec. per level (+0.54 at champion level 18)",rank:"1",effect:"UTILITY",cost:15},
    {id:5059,tier:1,name:"Lesser Glyph of Insight",description:"+0.32 magic penetration",rank:"1",effect:"MAGIC",cost:30},
    {id:5060,tier:1,name:"Lesser Glyph of Brilliance",description:"+0.02 magic penetration per level (+0.36 at champion level 18)",rank:"1",effect:"MAGIC",cost:30},
    {id:5061,tier:1,name:"Lesser Seal of Strength",description:"+0.24 attack damage",rank:"1",effect:"PHYSICAL",cost:15},
    {id:5062,tier:1,name:"Lesser Seal of Might",description:"+0.03 attack damage per level (+0.61 at champion level 18)",rank:"1",effect:"PHYSICAL",cost:15},
    {id:5063,tier:1,name:"Lesser Seal of Alacrity",description:"+0.42% attack speed",rank:"1",effect:"PHYSICAL",cost:30},
    {id:5064,tier:1,name:"Lesser Seal of Haste",description:"+0.01% attack speed per level (+0.18% at champion level 18)",rank:"1",effect:"PHYSICAL",cost:30},
    {id:5065,tier:1,name:"Lesser Seal of Furor",description:"+0.43% critical damage",rank:"1",effect:"PHYSICAL",cost:65},
    {id:5066,tier:1,name:"Lesser Seal of Carnage",description:"+0.01% critical damage per level (+0.18% at champion level 18)",rank:"1",effect:"PHYSICAL",cost:65},
    {id:5067,tier:1,name:"Lesser Seal of Malice",description:"+0.23% critical chance",rank:"1",effect:"PHYSICAL",cost:30},
    {id:5068,tier:1,name:"Lesser Seal of Brutality",description:"+0.01% critical chance per level (+0.18% at champion level 18)",rank:"1",effect:"PHYSICAL",cost:30},
    {id:5069,tier:1,name:"Lesser Seal of Desolation",description:"+0.43 armor penetration",rank:"1",effect:"PHYSICAL",cost:30},
    {id:5070,tier:1,name:"Lesser Seal of Precision",description:"+0.01 armor penetration per level (+0.18 at champion level 18)",rank:"1",effect:"PHYSICAL",cost:30},
    {id:5071,tier:1,name:"Lesser Seal of Fortitude",description:"+2.97 health",rank:"1",effect:"HEALTH",cost:65},
    {id:5072,tier:1,name:"Lesser Seal of Vitality",description:"+0.6 health per level (+10.8 at champion level 18)",rank:"1",effect:"HEALTH",cost:30},
    {id:5073,tier:1,name:"Lesser Seal of Resilience",description:"+0.78 armor",rank:"1",effect:"DEFENSE",cost:15},
    {id:5074,tier:1,name:"Lesser Seal of Defense",description:"+0.08 armor per level (+1.44 at champion level 18)",rank:"1",effect:"DEFENSE",cost:30},
    {id:5075,tier:1,name:"Lesser Seal of Warding",description:"+0.41 magic resist",rank:"1",effect:"DEFENSE",cost:15},
    {id:5076,tier:1,name:"Lesser Seal of Shielding",description:"+0.05 magic resist per level (+0.9 at champion level 18)",rank:"1",effect:"DEFENSE",cost:30},
    {id:5077,tier:1,name:"Lesser Seal of Vigor",description:"+0.24 health regen / 5 sec.",rank:"1",effect:"UTILITY",cost:65},
    {id:5078,tier:1,name:"Lesser Seal of Regeneration",description:"+0.06 health regen / 5 sec. per level (+1.08 at champion level 18)",rank:"1",effect:"UTILITY",cost:30},
    {id:5079,tier:1,name:"Lesser Seal of Evasion",description:"+0.42% dodge",rank:"1",effect:"UTILITY",cost:30},
    {id:5080,tier:1,name:"Lesser Seal of Elusion",description:"+0.03% dodge per level (+0.54% at champion level 18)",rank:"1",effect:"UTILITY",cost:30},
    {id:5081,tier:1,name:"Lesser Seal of Focus",description:"-0.16% cooldowns",rank:"1",effect:"UTILITY",cost:30},
    {id:5082,tier:1,name:"Lesser Seal of Celerity",description:"-0.01% cooldowns per level (-0.18% at champion level 18)",rank:"1",effect:"UTILITY",cost:30},
    {id:5083,tier:1,name:"Lesser Seal of Potency",description:"+0.33 ability power",rank:"1",effect:"MAGIC",cost:30},
    {id:5084,tier:1,name:"Lesser Seal of Force",description:"+0.06 ability power per level (+1.08 at champion level 18)",rank:"1",effect:"MAGIC",cost:30},
    {id:5085,tier:1,name:"Lesser Seal of Intellect",description:"+3.83 mana",rank:"1",effect:"MANA",cost:30},
    {id:5086,tier:1,name:"Lesser Seal of Knowledge",description:"+0.65 mana per level (+11.7 at champion level 18)",rank:"1",effect:"MANA",cost:30},
    {id:5087,tier:1,name:"Lesser Seal of Replenishment",description:"+0.23 mana regen / 5 sec.",rank:"1",effect:"UTILITY",cost:15},
    {id:5088,tier:1,name:"Lesser Seal of Clarity",description:"+0.036 mana regen / 5 sec. per level (+0.65 at champion level 18)",rank:"1",effect:"UTILITY",cost:15},
    {id:5089,tier:1,name:"Lesser Seal of Insight",description:"+0.32 magic penetration",rank:"1",effect:"MAGIC",cost:30},
    {id:5090,tier:1,name:"Lesser Seal of Brilliance",description:"+0.02 magic penetration per level (+0.36 at champion level 18)",rank:"1",effect:"MAGIC",cost:30},
    {id:5091,tier:1,name:"Lesser Quintessence of Strength",description:"+1.25 attack damage",rank:"1",effect:"PHYSICAL",cost:80},
    {id:5092,tier:1,name:"Lesser Quintessence of Might",description:"+0.14 attack damage per level (+2.52 at champion level 18)",rank:"1",effect:"PHYSICAL",cost:40},
    {id:5093,tier:1,name:"Lesser Quintessence of Alacrity",description:"+1.89% attack speed",rank:"1",effect:"PHYSICAL",cost:80},
    {id:5094,tier:1,name:"Lesser Quintessence of Haste",description:"+0.06% attack speed per level (+1.08% at champion level 18)",rank:"1",effect:"PHYSICAL",cost:40},
    {id:5095,tier:1,name:"Lesser Quintessence of Furor",description:"+2.48% critical damage",rank:"1",effect:"PHYSICAL",cost:80},
    {id:5096,tier:1,name:"Lesser Quintessence of Carnage",description:"+0.06% critical damage per level (+1.08% at champion level 18)",rank:"1",effect:"PHYSICAL",cost:40},
    {id:5097,tier:1,name:"Lesser Quintessence of Malice",description:"+1.03% critical chance",rank:"1",effect:"PHYSICAL",cost:80},
    {id:5098,tier:1,name:"Lesser Quintessence of Brutality",description:"+0.06% critical chance per level (+1.08% at champion level 18)",rank:"1",effect:"PHYSICAL",cost:40},
    {id:5099,tier:1,name:"Lesser Quintessence of Desolation",description:"+1.85 armor penetration",rank:"1",effect:"PHYSICAL",cost:80},
    {id:5100,tier:1,name:"Lesser Quintessence of Precision",description:"+0.06 armor penetration per level (+1.08 at champion level 18)",rank:"1",effect:"PHYSICAL",cost:40},
    {id:5101,tier:1,name:"Lesser Quintessence of Fortitude",description:"+14.5 health",rank:"1",effect:"HEALTH",cost:165},
    {id:5102,tier:1,name:"Lesser Quintessence of Vitality",description:"+1.5 health per level (+27 at champion level 18)",rank:"1",effect:"HEALTH",cost:165},
    {id:5103,tier:1,name:"Lesser Quintessence of Resilience",description:"+2.37 armor",rank:"1",effect:"DEFENSE",cost:80},
    {id:5104,tier:1,name:"Lesser Quintessence of Defense",description:"+0.21 armor per level (+3.78 at champion level 18)",rank:"1",effect:"DEFENSE",cost:80},
    {id:5105,tier:1,name:"Lesser Quintessence of Warding",description:"+2.5 magic resist",rank:"1",effect:"DEFENSE",cost:80},
    {id:5106,tier:1,name:"Lesser Quintessence of Shielding",description:"+0.21 magic resist per level (+3.78 at champion level 18)",rank:"1",effect:"DEFENSE",cost:80},
    {id:5107,tier:1,name:"Lesser Quintessence of Vigor",description:"+1.5 health regen / 5 sec.",rank:"1",effect:"UTILITY",cost:165},
    {id:5108,tier:1,name:"Lesser Quintessence of Regeneration",description:"+0.16 health regen / 5 sec. per level (+2.88 at champion level 18)",rank:"1",effect:"UTILITY",cost:165},
    {id:5109,tier:1,name:"Lesser Quintessence of Evasion",description:"+0.83% dodge",rank:"1",effect:"UTILITY",cost:80},
    {id:5110,tier:1,name:"Lesser Quintessence of Elusion",description:"+0.06% dodge per level (+1.08% at champion level 18)",rank:"1",effect:"UTILITY",cost:80},
    {id:5111,tier:1,name:"Lesser Quintessence of Focus",description:"-0.91% cooldowns",rank:"1",effect:"UTILITY",cost:165},
    {id:5112,tier:1,name:"Lesser Quintessence of Celerity",description:"-0.07% cooldowns per level (-1.26% at champion level 18)",rank:"1",effect:"UTILITY",cost:80},
    {id:5113,tier:1,name:"Lesser Quintessence of Potency",description:"+2.75 ability power",rank:"1",effect:"MAGIC",cost:80},
    {id:5114,tier:1,name:"Lesser Quintessence of Force",description:"+0.24 ability power per level (+4.32 at champion level 18)",rank:"1",effect:"MAGIC",cost:80},
    {id:5115,tier:1,name:"Lesser Quintessence of Intellect",description:"+20.83 mana",rank:"1",effect:"MANA",cost:80},
    {id:5116,tier:1,name:"Lesser Quintessence of Knowledge",description:"+2.31 mana per level (+41.58 at champion level 18)",rank:"1",effect:"MANA",cost:40},
    {id:5117,tier:1,name:"Lesser Quintessence of Replenishment",description:"+0.69 mana regen / 5 sec.",rank:"1",effect:"UTILITY",cost:80},
    {id:5118,tier:1,name:"Lesser Quintessence of Clarity",description:"+0.14 mana regen / 5 sec. per level (+2.52 at champion level 18)",rank:"1",effect:"UTILITY",cost:80},
    {id:5119,tier:1,name:"Lesser Quintessence of Insight",description:"+1.05 magic penetration",rank:"1",effect:"MAGIC",cost:80},
    {id:5120,tier:1,name:"Lesser Quintessence of Brilliance",description:"+0.06 magic penetration per level (+1.08 at champion level 18)",rank:"1",effect:"MAGIC",cost:40},
    {id:5121,tier:1,name:"Lesser Quintessence of Swiftness",description:"+0.83% movement speed",rank:"1",effect:"UTILITY",cost:165},
    {id:5122,tier:1,name:"Lesser Quintessence of Avarice",description:"+0.56 gold / 10 sec.",rank:"1",effect:"UTILITY",cost:165},
    {id:5123,tier:2,name:"Mark of Strength",description:"+0.74 attack damage",rank:"1",effect:"PHYSICAL",cost:80},
    {id:5124,tier:2,name:"Mark of Might",description:"+0.1 attack damage per level (+1.89 at champion level 18)",rank:"1",effect:"PHYSICAL",cost:165},
    {id:5125,tier:2,name:"Mark of Alacrity",description:"+1.32% attack speed",rank:"1",effect:"PHYSICAL",cost:165},
    {id:5126,tier:2,name:"Mark of Haste",description:"+0.04% attack speed per level (+0.72% at champion level 18)",rank:"1",effect:"PHYSICAL",cost:165},
    {id:5127,tier:2,name:"Mark of Furor",description:"+1.74% critical damage",rank:"1",effect:"PHYSICAL",cost:330},
    {id:5128,tier:2,name:"Mark of Carnage",description:"+0.04% critical damage per level (+0.72% at champion level 18)",rank:"1",effect:"PHYSICAL",cost:330},
    {id:5129,tier:2,name:"Mark of Malice",description:"+0.72% critical chance",rank:"1",effect:"PHYSICAL",cost:165},
    {id:5130,tier:2,name:"Mark of Brutality",description:"+0.04% critical chance per level (+0.72% at champion level 18)",rank:"1",effect:"PHYSICAL",cost:165},
    {id:5131,tier:2,name:"Mark of Desolation",description:"+1.29 armor penetration",rank:"1",effect:"PHYSICAL",cost:165},
    {id:5132,tier:2,name:"Mark of Precision",description:"+0.04 armor penetration per level (+0.72 at champion level 18)",rank:"1",effect:"PHYSICAL",cost:165},
    {id:5133,tier:2,name:"Mark of Fortitude",description:"+2.7 health",rank:"1",effect:"HEALTH",cost:165},
    {id:5134,tier:2,name:"Mark of Vitality",description:"+0.42 health per level (+7.56 at champion level 18)",rank:"1",effect:"HEALTH",cost:330},
    {id:5135,tier:2,name:"Mark of Resilience",description:"+0.71 armor",rank:"1",effect:"DEFENSE",cost:80},
    {id:5136,tier:2,name:"Mark of Defense",description:"+0.07 armor per level (+1.26 at champion level 18)",rank:"1",effect:"DEFENSE",cost:80},
    {id:5137,tier:2,name:"Mark of Warding",description:"+0.75 magic resist",rank:"1",effect:"DEFENSE",cost:80},
    {id:5138,tier:2,name:"Mark of Shielding",description:"+0.06 magic resist per level (+1.08 at champion level 18)",rank:"1",effect:"DEFENSE",cost:80},
    {id:5139,tier:2,name:"Mark of Vigor",description:"+0.21 health regen / 5 sec.",rank:"1",effect:"UTILITY",cost:165},
    {id:5140,tier:2,name:"Mark of Regeneration",description:"+0.07 health regen / 5 sec. per level (+1.26 at champion level 18)",rank:"1",effect:"UTILITY",cost:165},
    {id:5141,tier:2,name:"Mark of Evasion",description:"+0.29% dodge",rank:"1",effect:"UTILITY",cost:80},
    {id:5142,tier:2,name:"Mark of Elusion",description:"+0.02% dodge per level (+0.36% at champion level 18)",rank:"1",effect:"UTILITY",cost:80},
    {id:5143,tier:2,name:"Mark of Focus",description:"-0.13% cooldowns",rank:"1",effect:"UTILITY",cost:80},
    {id:5144,tier:2,name:"Mark of Celerity",description:"-0.01% cooldowns per level (-0.18% at champion level 18)",rank:"1",effect:"UTILITY",cost:80},
    {id:5145,tier:2,name:"Mark of Potency",description:"+0.46 ability power",rank:"1",effect:"MAGIC",cost:165},
    {id:5146,tier:2,name:"Mark of Force",description:"+0.08 ability power per level (+1.44 at champion level 18)",rank:"1",effect:"MAGIC",cost:165},
    {id:5147,tier:2,name:"Mark of Intellect",description:"+4.59 mana",rank:"1",effect:"MANA",cost:165},
    {id:5148,tier:2,name:"Mark of Knowledge",description:"+0.91 mana per level (+16.38 at champion level 18)",rank:"1",effect:"MANA",cost:165},
    {id:5149,tier:2,name:"Mark of Replenishment",description:"+0.2 mana regen / 5 sec.",rank:"1",effect:"UTILITY",cost:80},
    {id:5150,tier:2,name:"Mark of Clarity",description:"+0.06 mana regen / 5 sec. per level (+1.08 at champion level 18)",rank:"1",effect:"UTILITY",cost:80},
    {id:5151,tier:2,name:"Mark of Insight",description:"+0.74 magic penetration",rank:"1",effect:"MAGIC",cost:165},
    {id:5152,tier:2,name:"Mark of Brilliance",description:"+0.04 magic penetration per level (+0.72 at champion level 18)",rank:"1",effect:"MAGIC",cost:165},
    {id:5153,tier:2,name:"Glyph of Strength",description:"+0.22 attack damage",rank:"1",effect:"PHYSICAL",cost:205},
    {id:5154,tier:2,name:"Glyph of Might",description:"+0.03 attack damage per level (+0.57 at champion level 18)",rank:"1",effect:"PHYSICAL",cost:205},
    {id:5155,tier:2,name:"Glyph of Alacrity",description:"+0.5% attack speed",rank:"1",effect:"PHYSICAL",cost:165},
    {id:5156,tier:2,name:"Glyph of Haste",description:"+0.01% attack speed per level (+0.18% at champion level 18)",rank:"1",effect:"PHYSICAL",cost:165},
    {id:5157,tier:2,name:"Glyph of Furor",description:"+0.43% critical damage",rank:"1",effect:"PHYSICAL",cost:330},
    {id:5158,tier:2,name:"Glyph of Carnage",description:"+0.01% critical damage per level (+0.18% at champion level 18)",rank:"1",effect:"PHYSICAL",cost:330},
    {id:5159,tier:2,name:"Glyph of Malice",description:"+0.22% critical chance",rank:"1",effect:"PHYSICAL",cost:165},
    {id:5160,tier:2,name:"Glyph of Brutality",description:"+0.01% critical chance per level (+0.18% at champion level 18)",rank:"1",effect:"PHYSICAL",cost:165},
    {id:5161,tier:2,name:"Glyph of Desolation",description:"+0.3 armor penetration",rank:"1",effect:"PHYSICAL",cost:165},
    {id:5162,tier:2,name:"Glyph of Precision",description:"+0.01 armor penetration per level (+0.18 at champion level 18)",rank:"1",effect:"PHYSICAL",cost:165},
    {id:5163,tier:2,name:"Glyph of Fortitude",description:"+2.08 health",rank:"1",effect:"HEALTH",cost:165},
    {id:5164,tier:2,name:"Glyph of Vitality",description:"+0.42 health per level (+7.56 at champion level 18)",rank:"1",effect:"HEALTH",cost:330},
    {id:5165,tier:2,name:"Glyph of Resilience",description:"+0.55 armor",rank:"1",effect:"DEFENSE",cost:80},
    {id:5166,tier:2,name:"Glyph of Defense",description:"+0.08 armor per level (+1.44 at champion level 18)",rank:"1",effect:"DEFENSE",cost:80},
    {id:5167,tier:2,name:"Glyph of Warding",description:"+1.16 magic resist",rank:"1",effect:"DEFENSE",cost:80},
    {id:5168,tier:2,name:"Glyph of Shielding",description:"+0.12 magic resist per level (+2.16 at champion level 18)",rank:"1",effect:"DEFENSE",cost:80},
    {id:5169,tier:2,name:"Glyph of Vigor",description:"+0.21 health regen / 5 sec.",rank:"1",effect:"UTILITY",cost:330},
    {id:5170,tier:2,name:"Glyph of Regeneration",description:"+0.07 health regen / 5 sec. per level (+1.26 at champion level 18)",rank:"1",effect:"UTILITY",cost:330},
    {id:5171,tier:2,name:"Glyph of Evasion",description:"+0.29% dodge",rank:"1",effect:"UTILITY",cost:80},
    {id:5172,tier:2,name:"Glyph of Elusion",description:"+0.02% dodge per level (+0.36% at champion level 18)",rank:"1",effect:"UTILITY",cost:80},
    {id:5173,tier:2,name:"Glyph of Focus",description:"-0.51% cooldowns",rank:"1",effect:"UTILITY",cost:330},
    {id:5174,tier:2,name:"Glyph of Celerity",description:"-0.04% cooldowns per level (-0.72% at champion level 18)",rank:"1",effect:"UTILITY",cost:165},
    {id:5175,tier:2,name:"Glyph of Potency",description:"+0.77 ability power",rank:"1",effect:"MAGIC",cost:165},
    {id:5176,tier:2,name:"Glyph of Force",description:"+0.13 ability power per level (+2.34 at champion level 18)",rank:"1",effect:"MAGIC",cost:165},
    {id:5177,tier:2,name:"Glyph of Intellect",description:"+8.75 mana",rank:"1",effect:"MANA",cost:165},
    {id:5178,tier:2,name:"Glyph of Knowledge",description:"+1.1 mana per level (+19.8 at champion level 18)",rank:"1",effect:"MANA",cost:165},
    {id:5179,tier:2,name:"Glyph of Replenishment",description:"+0.24 mana regen / 5 sec.",rank:"1",effect:"UTILITY",cost:165},
    {id:5180,tier:2,name:"Glyph of Clarity",description:"+0.04 mana regen / 5 sec. per level (+0.72 at champion level 18)",rank:"1",effect:"UTILITY",cost:80},
    {id:5181,tier:2,name:"Glyph of Insight",description:"+0.44 magic penetration",rank:"1",effect:"MAGIC",cost:165},
    {id:5182,tier:2,name:"Glyph of Brilliance",description:"+0.02 magic penetration per level (+0.36 at champion level 18)",rank:"1",effect:"MAGIC",cost:165},
    {id:5183,tier:2,name:"Seal of Strength",description:"+0.33 attack damage",rank:"1",effect:"PHYSICAL",cost:80},
    {id:5184,tier:2,name:"Seal of Might",description:"+0.05 attack damage per level (+0.85 at champion level 18)",rank:"1",effect:"PHYSICAL",cost:80},
    {id:5185,tier:2,name:"Seal of Alacrity",description:"+0.59% attack speed",rank:"1",effect:"PHYSICAL",cost:165},
    {id:5186,tier:2,name:"Seal of Haste",description:"+0.02% attack speed per level (+0.36% at champion level 18)",rank:"1",effect:"PHYSICAL",cost:165},
    {id:5187,tier:2,name:"Seal of Furor",description:"+0.61% critical damage",rank:"1",effect:"PHYSICAL",cost:330},
    {id:5188,tier:2,name:"Seal of Carnage",description:"+0.02% critical damage per level (+0.36% at champion level 18)",rank:"1",effect:"PHYSICAL",cost:330},
    {id:5189,tier:2,name:"Seal of Malice",description:"+0.32% critical chance",rank:"1",effect:"PHYSICAL",cost:165},
    {id:5190,tier:2,name:"Seal of Brutality",description:"+0.01% critical chance per level (+0.18% at champion level 18)",rank:"1",effect:"PHYSICAL",cost:165},
    {id:5191,tier:2,name:"Seal of Desolation",description:"+0.61 armor penetration",rank:"1",effect:"PHYSICAL",cost:165},
    {id:5192,tier:2,name:"Seal of Precision",description:"+0.01 armor penetration per level (+0.18 at champion level 18)",rank:"1",effect:"PHYSICAL",cost:165},
    {id:5193,tier:2,name:"Seal of Fortitude",description:"+4.16 health",rank:"1",effect:"HEALTH",cost:330},
    {id:5194,tier:2,name:"Seal of Vitality",description:"+0.84 health per level (+15.12 at champion level 18)",rank:"1",effect:"HEALTH",cost:165},
    {id:5195,tier:2,name:"Seal of Resilience",description:"+1.09 armor",rank:"1",effect:"DEFENSE",cost:80},
    {id:5196,tier:2,name:"Seal of Defense",description:"+0.12 armor per level (+2.16 at champion level 18)",rank:"1",effect:"DEFENSE",cost:165},
    {id:5197,tier:2,name:"Seal of Warding",description:"+0.58 magic resist",rank:"1",effect:"DEFENSE",cost:80},
    {id:5198,tier:2,name:"Seal of Shielding",description:"+0.08 magic resist per level (+1.44 at champion level 18)",rank:"1",effect:"DEFENSE",cost:165},
    {id:5199,tier:2,name:"Seal of Vigor",description:"+0.34 health regen / 5 sec.",rank:"1",effect:"UTILITY",cost:330},
    {id:5200,tier:2,name:"Seal of Regeneration",description:"+0.09 health regen / 5 sec. per level (+1.62 at champion level 18)",rank:"1",effect:"UTILITY",cost:165},
    {id:5201,tier:2,name:"Seal of Evasion",description:"+0.58% dodge",rank:"1",effect:"UTILITY",cost:165},
    {id:5202,tier:2,name:"Seal of Elusion",description:"+0.04% dodge per level (+0.72% at champion level 18)",rank:"1",effect:"UTILITY",cost:165},
    {id:5203,tier:2,name:"Seal of Focus",description:"-0.23% cooldowns",rank:"1",effect:"UTILITY",cost:165},
    {id:5204,tier:2,name:"Seal of Celerity",description:"-0.02% cooldowns per level (-0.36% at champion level 18)",rank:"1",effect:"UTILITY",cost:165},
    {id:5205,tier:2,name:"Seal of Potency",description:"+0.46 ability power",rank:"1",effect:"MAGIC",cost:165},
    {id:5206,tier:2,name:"Seal of Force",description:"+0.08 ability power per level (+1.44 at champion level 18)",rank:"1",effect:"MAGIC",cost:165},
    {id:5207,tier:2,name:"Seal of Intellect",description:"+5.36 mana",rank:"1",effect:"MANA",cost:165},
    {id:5208,tier:2,name:"Seal of Knowledge",description:"+0.91 mana per level (+16.38 at champion level 18)",rank:"1",effect:"MANA",cost:165},
    {id:5209,tier:2,name:"Seal of Replenishment",description:"+0.32 mana regen / 5 sec.",rank:"1",effect:"UTILITY",cost:80},
    {id:5210,tier:2,name:"Seal of Clarity",description:"+0.05 mana regen / 5 sec. per level (+0.9 at champion level 18)",rank:"1",effect:"UTILITY",cost:80},
    {id:5211,tier:2,name:"Seal of Insight",description:"+0.44 magic penetration",rank:"1",effect:"MAGIC",cost:165},
    {id:5212,tier:2,name:"Seal of Brilliance",description:"+0.02 magic penetration per level (+0.36 at champion level 18)",rank:"1",effect:"MAGIC",cost:165},
    {id:5213,tier:2,name:"Quintessence of Strength",description:"+1.75 attack damage",rank:"1",effect:"PHYSICAL",cost:410},
    {id:5214,tier:2,name:"Quintessence of Might",description:"+0.19 attack damage per level (+3.42 at champion level 18)",rank:"1",effect:"PHYSICAL",cost:205},
    {id:5215,tier:2,name:"Quintessence of Alacrity",description:"+2.64% attack speed",rank:"1",effect:"PHYSICAL",cost:410},
    {id:5216,tier:2,name:"Quintessence of Haste",description:"+0.09% attack speed per level (+1.62% at champion level 18)",rank:"1",effect:"PHYSICAL",cost:205},
    {id:5217,tier:2,name:"Quintessence of Furor",description:"+3.47% critical damage",rank:"1",effect:"PHYSICAL",cost:410},
    {id:5218,tier:2,name:"Quintessence of Carnage",description:"+0.09% critical damage per level (+1.62% at champion level 18)",rank:"1",effect:"PHYSICAL",cost:205},
    {id:5219,tier:2,name:"Quintessence of Malice",description:"+1.44% critical chance",rank:"1",effect:"PHYSICAL",cost:410},
    {id:5220,tier:2,name:"Quintessence of Brutality",description:"+0.09% critical chance per level (+1.62% at champion level 18)",rank:"1",effect:"PHYSICAL",cost:205},
    {id:5221,tier:2,name:"Quintessence of Desolation",description:"+2.59 armor penetration",rank:"1",effect:"PHYSICAL",cost:410},
    {id:5222,tier:2,name:"Quintessence of Precision",description:"+0.09 armor penetration per level (+1.62 at champion level 18)",rank:"1",effect:"PHYSICAL",cost:205},
    {id:5223,tier:2,name:"Quintessence of Fortitude",description:"+20 health",rank:"1",effect:"HEALTH",cost:820},
    {id:5224,tier:2,name:"Quintessence of Vitality",description:"+2.1 health per level (+37.8 at champion level 18)",rank:"1",effect:"HEALTH",cost:820},
    {id:5225,tier:2,name:"Quintessence of Resilience",description:"+3.32 armor",rank:"1",effect:"DEFENSE",cost:410},
    {id:5226,tier:2,name:"Quintessence of Defense",description:"+0.29 armor per level (+5.22 at champion level 18)",rank:"1",effect:"DEFENSE",cost:410},
    {id:5227,tier:2,name:"Quintessence of Warding",description:"+3.5 magic resist",rank:"1",effect:"DEFENSE",cost:410},
    {id:5228,tier:2,name:"Quintessence of Shielding",description:"+0.29 magic resist per level (+5.22 at champion level 18)",rank:"1",effect:"DEFENSE",cost:410},
    {id:5229,tier:2,name:"Quintessence of Vigor",description:"+2.1 health regen / 5 sec.",rank:"1",effect:"UTILITY",cost:820},
    {id:5230,tier:2,name:"Quintessence of Regeneration",description:"+0.22 health regen / 5 sec. per level (+3.96 at champion level 18)",rank:"1",effect:"UTILITY",cost:820},
    {id:5231,tier:2,name:"Quintessence of Evasion",description:"+1.17% dodge",rank:"1",effect:"UTILITY",cost:410},
    {id:5232,tier:2,name:"Quintessence of Elusion",description:"+0.09% dodge per level (+1.62% at champion level 18)",rank:"1",effect:"UTILITY",cost:410},
    {id:5233,tier:2,name:"Quintessence of Focus",description:"-1.27% cooldowns",rank:"1",effect:"UTILITY",cost:820},
    {id:5234,tier:2,name:"Quintessence of Celerity",description:"-0.1% cooldowns per level (-1.8% at champion level 18)",rank:"1",effect:"UTILITY",cost:410},
    {id:5235,tier:2,name:"Quintessence of Potency",description:"+3.85 ability power",rank:"1",effect:"MAGIC",cost:410},
    {id:5236,tier:2,name:"Quintessence of Force",description:"+0.34 ability power per level (+6.12 at champion level 18)",rank:"1",effect:"MAGIC",cost:410},
    {id:5237,tier:2,name:"Quintessence of Intellect",description:"+29.17 mana",rank:"1",effect:"MANA",cost:410},
    {id:5238,tier:2,name:"Quintessence of Knowledge",description:"+3.24 mana per level (+58.32 at champion level 18)",rank:"1",effect:"MANA",cost:205},
    {id:5239,tier:2,name:"Quintessence of Replenishment",description:"+0.97 mana regen / 5 sec.",rank:"1",effect:"UTILITY",cost:410},
    {id:5240,tier:2,name:"Quintessence of Clarity",description:"+0.19 mana regen / 5 sec. per level (+3.42 at champion level 18)",rank:"1",effect:"UTILITY",cost:410},
    {id:5241,tier:2,name:"Quintessence of Insight",description:"+1.47 magic penetration",rank:"1",effect:"MAGIC",cost:410},
    {id:5242,tier:2,name:"Quintessence of Brilliance",description:"+0.09 magic penetration per level (+1.62 at champion level 18)",rank:"1",effect:"MAGIC",cost:205},
    {id:5243,tier:2,name:"Quintessence of Swiftness",description:"+1.17% movement speed",rank:"1",effect:"UTILITY",cost:820},
    {id:5244,tier:2,name:"Quintessence of Avarice",description:"+0.78 gold / 10 sec.",rank:"1",effect:"UTILITY",cost:820},
    {id:5245,tier:3,name:"Greater Mark of Strength",description:"+0.95 attack damage",rank:"1",effect:"PHYSICAL",cost:205},
    {id:5246,tier:3,name:"Greater Mark of Might",description:"+0.13 attack damage per level (+2.43 at champion level 18)",rank:"1",effect:"PHYSICAL",cost:410},
    {id:5247,tier:3,name:"Greater Mark of Alacrity",description:"+1.7% attack speed",rank:"1",effect:"PHYSICAL",cost:410},
    {id:5248,tier:3,name:"Greater Mark of Haste",description:"+0.05% attack speed per level (+0.9% at champion level 18)",rank:"1",effect:"PHYSICAL",cost:410},
    {id:5249,tier:3,name:"Greater Mark of Furor",description:"+2.23% critical damage",rank:"1",effect:"PHYSICAL",cost:820},
    {id:5250,tier:3,name:"Greater Mark of Carnage",description:"+0.05% critical damage per level (+0.9% at champion level 18)",rank:"1",effect:"PHYSICAL",cost:820},
    {id:5251,tier:3,name:"Greater Mark of Malice",description:"+0.93% critical chance",rank:"1",effect:"PHYSICAL",cost:410},
    {id:5252,tier:3,name:"Greater Mark of Brutality",description:"+0.05% critical chance per level (+0.9% at champion level 18)",rank:"1",effect:"PHYSICAL",cost:410},
    {id:5253,tier:3,name:"Greater Mark of Desolation",description:"+1.66 armor penetration",rank:"1",effect:"PHYSICAL",cost:410},
    {id:5254,tier:3,name:"Greater Mark of Precision",description:"+0.05 armor penetration per level (+0.9 at champion level 18)",rank:"1",effect:"PHYSICAL",cost:410},
    {id:5255,tier:3,name:"Greater Mark of Fortitude",description:"+3.47 health",rank:"1",effect:"HEALTH",cost:410},
    {id:5256,tier:3,name:"Greater Mark of Vitality",description:"+0.54 health per level (+9.72 at champion level 18)",rank:"1",effect:"HEALTH",cost:820},
    {id:5257,tier:3,name:"Greater Mark of Resilience",description:"+0.91 armor",rank:"1",effect:"DEFENSE",cost:205},
    {id:5258,tier:3,name:"Greater Mark of Defense",description:"+0.09 armor per level (+1.62 at champion level 18)",rank:"1",effect:"DEFENSE",cost:205},
    {id:5259,tier:3,name:"Greater Mark of Warding",description:"+0.97 magic resist",rank:"1",effect:"DEFENSE",cost:205},
    {id:5260,tier:3,name:"Greater Mark of Shielding",description:"+0.07 magic resist per level (+1.26 at champion level 18)",rank:"1",effect:"DEFENSE",cost:205},
    {id:5261,tier:3,name:"Greater Mark of Vigor",description:"+0.27 health regen / 5 sec.",rank:"1",effect:"UTILITY",cost:410},
    {id:5262,tier:3,name:"Greater Mark of Regeneration",description:"+0.08 health regen / 5 sec. per level (+1.44 at champion level 18)",rank:"1",effect:"UTILITY",cost:410},
    {id:5263,tier:3,name:"Greater Mark of Evasion",description:"+0.38% dodge",rank:"1",effect:"UTILITY",cost:205},
    {id:5264,tier:3,name:"Greater Mark of Elusion",description:"+0.02% dodge per level (+0.36% at champion level 18)",rank:"1",effect:"UTILITY",cost:205},
    {id:5265,tier:3,name:"Greater Mark of Focus",description:"-0.16% cooldowns",rank:"1",effect:"UTILITY",cost:410},
    {id:5266,tier:3,name:"Greater Mark of Celerity",description:"-0.02% cooldowns per level (-0.36% at champion level 18)",rank:"1",effect:"UTILITY",cost:410},
    {id:5267,tier:3,name:"Greater Mark of Potency",description:"+0.59 ability power",rank:"1",effect:"MAGIC",cost:410},
    {id:5268,tier:3,name:"Greater Mark of Force",description:"+0.1 ability power per level (+1.8 at champion level 18)",rank:"1",effect:"MAGIC",cost:410},
    {id:5269,tier:3,name:"Greater Mark of Intellect",description:"+5.91 mana",rank:"1",effect:"MANA",cost:410},
    {id:5270,tier:3,name:"Greater Mark of Knowledge",description:"+1.17 mana per level (+21.06 at champion level 18)",rank:"1",effect:"MANA",cost:410},
    {id:5271,tier:3,name:"Greater Mark of Replenishment",description:"+0.26 mana regen / 5 sec.",rank:"1",effect:"UTILITY",cost:205},
    {id:5272,tier:3,name:"Greater Mark of Clarity",description:"+0.08 mana regen / 5 sec. per level (+1.44 at champion level 18)",rank:"1",effect:"UTILITY",cost:205},
    {id:5273,tier:3,name:"Greater Mark of Insight",description:"+0.95 magic penetration",rank:"1",effect:"MAGIC",cost:410},
    {id:5274,tier:3,name:"Greater Mark of Brilliance",description:"+0.05 magic penetration per level (+0.9 at champion level 18)",rank:"1",effect:"MAGIC",cost:410},
    {id:5275,tier:3,name:"Greater Glyph of Strength",description:"+0.28 attack damage",rank:"1",effect:"PHYSICAL",cost:205},
    {id:5276,tier:3,name:"Greater Glyph of Might",description:"+0.04 attack damage per level (+0.73 at champion level 18)",rank:"1",effect:"PHYSICAL",cost:205},
    {id:5277,tier:3,name:"Greater Glyph of Alacrity",description:"+0.64% attack speed",rank:"1",effect:"PHYSICAL",cost:410},
    {id:5278,tier:3,name:"Greater Glyph of Haste",description:"+0.01% attack speed per level (+0.18% at champion level 18)",rank:"1",effect:"PHYSICAL",cost:410},
    {id:5279,tier:3,name:"Greater Glyph of Furor",description:"+0.56% critical damage",rank:"1",effect:"PHYSICAL",cost:820},
    {id:5280,tier:3,name:"Greater Glyph of Carnage",description:"+0.01% critical damage per level (+0.18% at champion level 18)",rank:"1",effect:"PHYSICAL",cost:820},
    {id:5281,tier:3,name:"Greater Glyph of Malice",description:"+0.28% critical chance",rank:"1",effect:"PHYSICAL",cost:410},
    {id:5282,tier:3,name:"Greater Glyph of Brutality",description:"+0.01% critical chance per level (+0.18% at champion level 18)",rank:"1",effect:"PHYSICAL",cost:410},
    {id:5283,tier:3,name:"Greater Glyph of Desolation",description:"+0.39 armor penetration",rank:"1",effect:"PHYSICAL",cost:410},
    {id:5284,tier:3,name:"Greater Glyph of Precision",description:"+0.01 armor penetration per level (+0.18 at champion level 18)",rank:"1",effect:"PHYSICAL",cost:410},
    {id:5285,tier:3,name:"Greater Glyph of Fortitude",description:"+2.67 health",rank:"1",effect:"HEALTH",cost:410},
    {id:5286,tier:3,name:"Greater Glyph of Vitality",description:"+0.54 health per level (+9.72 at champion level 18)",rank:"1",effect:"HEALTH",cost:820},
    {id:5287,tier:3,name:"Greater Glyph of Resilience",description:"+0.7 armor",rank:"1",effect:"DEFENSE",cost:205},
    {id:5288,tier:3,name:"Greater Glyph of Defense",description:"+0.1 armor per level (+1.8 at champion level 18)",rank:"1",effect:"DEFENSE",cost:205},
    {id:5289,tier:3,name:"Greater Glyph of Warding",description:"+1.49 magic resist",rank:"1",effect:"DEFENSE",cost:205},
    {id:5290,tier:3,name:"Greater Glyph of Shielding",description:"+0.15 magic resist per level (+2.7 at champion level 18)",rank:"1",effect:"DEFENSE",cost:205},
    {id:5291,tier:3,name:"Greater Glyph of Vigor",description:"+0.27 health regen / 5 sec.",rank:"1",effect:"UTILITY",cost:820},
    {id:5292,tier:3,name:"Greater Glyph of Regeneration",description:"+0.09 health regen / 5 sec. per level (+1.62 at champion level 18)",rank:"1",effect:"UTILITY",cost:820},
    {id:5293,tier:3,name:"Greater Glyph of Evasion",description:"+0.38% dodge",rank:"1",effect:"UTILITY",cost:205},
    {id:5294,tier:3,name:"Greater Glyph of Elusion",description:"+0.02% dodge per level (+0.36% at champion level 18)",rank:"1",effect:"UTILITY",cost:205},
    {id:5295,tier:3,name:"Greater Glyph of Focus",description:"-0.65% cooldowns",rank:"1",effect:"UTILITY",cost:820},
    {id:5296,tier:3,name:"Greater Glyph of Celerity",description:"-0.05% cooldowns per level (-0.9% at champion level 18)",rank:"1",effect:"UTILITY",cost:410},
    {id:5297,tier:3,name:"Greater Glyph of Potency",description:"+0.99 ability power",rank:"1",effect:"MAGIC",cost:410},
    {id:5298,tier:3,name:"Greater Glyph of Force",description:"+0.17 ability power per level (+3.06 at champion level 18)",rank:"1",effect:"MAGIC",cost:410},
    {id:5299,tier:3,name:"Greater Glyph of Intellect",description:"+11.25 mana",rank:"1",effect:"MANA",cost:410},
    {id:5300,tier:3,name:"Greater Glyph of Knowledge",description:"+1.42 mana per level (+25.56 at champion level 18)",rank:"1",effect:"MANA",cost:410},
    {id:5301,tier:3,name:"Greater Glyph of Replenishment",description:"+0.31 mana regen / 5 sec.",rank:"1",effect:"UTILITY",cost:410},
    {id:5302,tier:3,name:"Greater Glyph of Clarity",description:"+0.055 mana regen / 5 sec. per level (+0.99 at champion level 18)",rank:"1",effect:"UTILITY",cost:205},
    {id:5303,tier:3,name:"Greater Glyph of Insight",description:"+0.57 magic penetration",rank:"1",effect:"MAGIC",cost:410},
    {id:5304,tier:3,name:"Greater Glyph of Brilliance",description:"+0.03 magic penetration per level (+0.54 at champion level 18)",rank:"1",effect:"MAGIC",cost:410},
    {id:5305,tier:3,name:"Greater Seal of Strength",description:"+0.43 attack damage",rank:"1",effect:"PHYSICAL",cost:205},
    {id:5306,tier:3,name:"Greater Seal of Might",description:"+0.06 attack damage per level (+1.09 at champion level 18)",rank:"1",effect:"PHYSICAL",cost:205},
    {id:5307,tier:3,name:"Greater Seal of Alacrity",description:"+0.76% attack speed",rank:"1",effect:"PHYSICAL",cost:410},
    {id:5308,tier:3,name:"Greater Seal of Haste",description:"+0.02% attack speed per level (+0.36% at champion level 18)",rank:"1",effect:"PHYSICAL",cost:410},
    {id:5309,tier:3,name:"Greater Seal of Furor",description:"+0.78% critical damage",rank:"1",effect:"PHYSICAL",cost:820},
    {id:5310,tier:3,name:"Greater Seal of Carnage",description:"+0.02% critical damage per level (+0.36% at champion level 18)",rank:"1",effect:"PHYSICAL",cost:820},
    {id:5311,tier:3,name:"Greater Seal of Malice",description:"+0.42% critical chance",rank:"1",effect:"PHYSICAL",cost:410},
    {id:5312,tier:3,name:"Greater Seal of Brutality",description:"+0.02% critical chance per level (+0.36% at champion level 18)",rank:"1",effect:"PHYSICAL",cost:410},
    {id:5313,tier:3,name:"Greater Seal of Desolation",description:"+0.78 armor penetration",rank:"1",effect:"PHYSICAL",cost:410},
    {id:5314,tier:3,name:"Greater Seal of Precision",description:"+0.02 armor penetration per level (+0.36 at champion level 18)",rank:"1",effect:"PHYSICAL",cost:410},
    {id:5315,tier:3,name:"Greater Seal of Fortitude",description:"+5.35 health",rank:"1",effect:"HEALTH",cost:820},
    {id:5316,tier:3,name:"Greater Seal of Vitality",description:"+1.08 health per level (+19.44 at champion level 18)",rank:"1",effect:"HEALTH",cost:410},
    {id:5317,tier:3,name:"Greater Seal of Resilience",description:"+1.41 armor",rank:"1",effect:"DEFENSE",cost:205},
    {id:5318,tier:3,name:"Greater Seal of Defense",description:"+0.15 armor per level (+2.7 at champion level 18)",rank:"1",effect:"DEFENSE",cost:410},
    {id:5319,tier:3,name:"Greater Seal of Warding",description:"+0.74 magic resist",rank:"1",effect:"DEFENSE",cost:205},
    {id:5320,tier:3,name:"Greater Seal of Shielding",description:"+0.1 magic resist per level (+1.8 at champion level 18)",rank:"1",effect:"DEFENSE",cost:410},
    {id:5321,tier:3,name:"Greater Seal of Vigor",description:"+0.43 health regen / 5 sec.",rank:"1",effect:"UTILITY",cost:820},
    {id:5322,tier:3,name:"Greater Seal of Regeneration",description:"+0.11 health regen / 5 sec. per level (+1.98 at champion level 18)",rank:"1",effect:"UTILITY",cost:410},
    {id:5323,tier:3,name:"Greater Seal of Evasion",description:"+0.75% dodge",rank:"1",effect:"UTILITY",cost:410},
    {id:5324,tier:3,name:"Greater Seal of Elusion",description:"+0.05% dodge per level (+0.9% at champion level 18)",rank:"1",effect:"UTILITY",cost:410},
    {id:5325,tier:3,name:"Greater Seal of Focus",description:"-0.29% cooldowns",rank:"1",effect:"UTILITY",cost:410},
    {id:5326,tier:3,name:"Greater Seal of Celerity",description:"-0.03% cooldowns per level (-0.54% at champion level 18)",rank:"1",effect:"UTILITY",cost:410},
    {id:5327,tier:3,name:"Greater Seal of Potency",description:"+0.59 ability power",rank:"1",effect:"MAGIC",cost:410},
    {id:5328,tier:3,name:"Greater Seal of Force",description:"+0.1 ability power per level (+1.8 at champion level 18)",rank:"1",effect:"MAGIC",cost:410},
    {id:5329,tier:3,name:"Greater Seal of Intellect",description:"+6.89 mana",rank:"1",effect:"MANA",cost:410},
    {id:5330,tier:3,name:"Greater Seal of Knowledge",description:"+1.17 mana per level (+21.06 at champion level 18)",rank:"1",effect:"MANA",cost:410},
    {id:5331,tier:3,name:"Greater Seal of Replenishment",description:"+0.41 mana regen / 5 sec.",rank:"1",effect:"UTILITY",cost:205},
    {id:5332,tier:3,name:"Greater Seal of Clarity",description:"+0.065 mana regen / 5 sec. per level (+1.17 at champion level 18)",rank:"1",effect:"UTILITY",cost:205},
    {id:5333,tier:3,name:"Greater Seal of Insight",description:"+0.57 magic penetration",rank:"1",effect:"MAGIC",cost:410},
    {id:5334,tier:3,name:"Greater Seal of Brilliance",description:"+0.03 magic penetration per level (+0.54 at champion level 18)",rank:"1",effect:"MAGIC",cost:410},
    {id:5335,tier:3,name:"Greater Quintessence of Strength",description:"+2.25 attack damage",rank:"1",effect:"PHYSICAL",cost:1025},
    {id:5336,tier:3,name:"Greater Quintessence of Might",description:"+0.25 attack damage per level (+4.5 at champion level 18)",rank:"1",effect:"PHYSICAL",cost:515},
    {id:5337,tier:3,name:"Greater Quintessence of Alacrity",description:"+3.4% attack speed",rank:"1",effect:"PHYSICAL",cost:1025},
    {id:5338,tier:3,name:"Greater Quintessence of Haste",description:"+0.11% attack speed per level (+1.98% at champion level 18)",rank:"1",effect:"PHYSICAL",cost:515},
    {id:5339,tier:3,name:"Greater Quintessence of Furor",description:"+4.46% critical damage",rank:"1",effect:"PHYSICAL",cost:1025},
    {id:5340,tier:3,name:"Greater Quintessence of Carnage",description:"+0.11% critical damage per level (+1.98% at champion level 18)",rank:"1",effect:"PHYSICAL",cost:515},
    {id:5341,tier:3,name:"Greater Quintessence of Malice",description:"+1.86% critical chance",rank:"1",effect:"PHYSICAL",cost:1025},
    {id:5342,tier:3,name:"Greater Quintessence of Brutality",description:"+0.11% critical chance per level (+1.98% at champion level 18)",rank:"1",effect:"PHYSICAL",cost:515},
    {id:5343,tier:3,name:"Greater Quintessence of Desolation",description:"+3.33 armor penetration",rank:"1",effect:"PHYSICAL",cost:1025},
    {id:5344,tier:3,name:"Greater Quintessence of Precision",description:"+0.11 armor penetration per level (+1.98 at champion level 18)",rank:"1",effect:"PHYSICAL",cost:515},
    {id:5345,tier:3,name:"Greater Quintessence of Fortitude",description:"+26 health",rank:"1",effect:"HEALTH",cost:2050},
    {id:5346,tier:3,name:"Greater Quintessence of Vitality",description:"+2.7 health per level (+48.6 at champion level 18)",rank:"1",effect:"HEALTH",cost:2050},
    {id:5347,tier:3,name:"Greater Quintessence of Resilience",description:"+4.26 armor",rank:"1",effect:"DEFENSE",cost:1025},
    {id:5348,tier:3,name:"Greater Quintessence of Defense",description:"+0.38 armor per level (+6.84 at champion level 18)",rank:"1",effect:"DEFENSE",cost:1025},
    {id:5349,tier:3,name:"Greater Quintessence of Warding",description:"+4.5 magic resist",rank:"1",effect:"DEFENSE",cost:1025},
    {id:5350,tier:3,name:"Greater Quintessence of Shielding",description:"+0.37 magic resist per level (+6.66 at champion level 18)",rank:"1",effect:"DEFENSE",cost:1025},
    {id:5351,tier:3,name:"Greater Quintessence of Vigor",description:"+2.7 health regen / 5 sec.",rank:"1",effect:"UTILITY",cost:2050},
    {id:5352,tier:3,name:"Greater Quintessence of Regeneration",description:"+0.28 health regen / 5 sec. per level (+5.04 at champion level 18)",rank:"1",effect:"UTILITY",cost:2050},
    {id:5353,tier:3,name:"Greater Quintessence of Evasion",description:"+1.5% dodge",rank:"1",effect:"UTILITY",cost:1025},
    {id:5354,tier:3,name:"Greater Quintessence of Elusion",description:"+0.11% dodge per level (+1.98% at champion level 18)",rank:"1",effect:"UTILITY",cost:1025},
    {id:5355,tier:3,name:"Greater Quintessence of Focus",description:"-1.64% cooldowns",rank:"1",effect:"UTILITY",cost:2050},
    {id:5356,tier:3,name:"Greater Quintessence of Celerity",description:"-0.13% cooldowns per level (-2.34% at champion level 18)",rank:"1",effect:"UTILITY",cost:1025},
    {id:5357,tier:3,name:"Greater Quintessence of Potency",description:"+4.95 ability power",rank:"1",effect:"MAGIC",cost:1025},
    {id:5358,tier:3,name:"Greater Quintessence of Force",description:"+0.43 ability power per level (+7.74 at champion level 18)",rank:"1",effect:"MAGIC",cost:1025},
    {id:5359,tier:3,name:"Greater Quintessence of Intellect",description:"+37.5 mana",rank:"1",effect:"MANA",cost:1025},
    {id:5360,tier:3,name:"Greater Quintessence of Knowledge",description:"+4.17 mana per level (+75.06 at champion level 18)",rank:"1",effect:"MANA",cost:515},
    {id:5361,tier:3,name:"Greater Quintessence of Replenishment",description:"+1.25 mana regen / 5 sec.",rank:"1",effect:"UTILITY",cost:1025},
    {id:5362,tier:3,name:"Greater Quintessence of Clarity",description:"+0.24 mana regen / 5 sec. per level (+4.32 at champion level 18)",rank:"1",effect:"UTILITY",cost:1025},
    {id:5363,tier:3,name:"Greater Quintessence of Insight",description:"+1.89 magic penetration",rank:"1",effect:"MAGIC",cost:1025},
    {id:5364,tier:3,name:"Greater Quintessence of Brilliance",description:"+0.11 magic penetration per level (+1.98 at champion level 18)",rank:"1",effect:"MAGIC",cost:515},
    {id:5365,tier:3,name:"Greater Quintessence of Swiftness",description:"+1.5% movement speed",rank:"1",effect:"UTILITY",cost:2050},
    {id:5366,tier:3,name:"Greater Quintessence of Revival",description:"-5% time dead",rank:"1",effect:"UTILITY",cost:1025},
    {id:5367,tier:3,name:"Greater Quintessence of Avarice",description:"+1 gold / 10 sec.",rank:"1",effect:"UTILITY",cost:515},
    {id:5368,tier:3,name:"Greater Quintessence of Wisdom",description:"+2% experience gained",rank:"1",effect:"UTILITY",cost:2050},
    {id:5369,tier:3,name:"Greater Seal of Meditation",description:"+0.63 Energy regen/5 sec",rank:"1",effect:"MANA",cost:820},
    {id:5370,tier:3,name:"Greater Seal of Lucidity",description:"+0.064 Energy regen/5 sec per level (+1.15 at champion level 18)",rank:"1",effect:"MANA",cost:820},
    {id:5371,tier:3,name:"Greater Glyph of Acumen",description:"+2.2 Energy",rank:"1",effect:"MANA",cost:820},
    {id:5372,tier:3,name:"Greater Glyph of Sapience",description:"+0.161 Energy/level (+2.89 at level 18)",rank:"1",effect:"MANA",cost:820},
    {id:5373,tier:3,name:"Greater Quintessence of Meditation",description:"+1.575 Energy regen/5 sec",rank:"1",effect:"MANA",cost:2050},
    {id:5374,tier:3,name:"Greater Quintessence of Acumen",description:"+5.4 Energy",rank:"1",effect:"MANA",cost:1025},
    {id:5375,tier:3,name:"Greater Quintessence of Perseverance",description:"UNIQUE: Reduces the duration of stun effects on your Champion by 15%",rank:"1",effect:"UTILITY",cost:1025},
    {id:5376,tier:3,name:"Greater Quintessence of Longevity",description:"UNIQUE: Reduces the duration of slow and silence effects on your Champion by 15%",rank:"1",effect:"UTILITY",cost:1025},
    {id:5377,tier:3,name:"Greater Quintessence of Mettle",description:"UNIQUE: When you kill or assist in killing a champion, you permanently gain 3 health plus an additional 3 health the first time this occurs.",rank:"1",effect:"UTILITY",cost:1025},
    {id:5378,tier:3,name:"Greater Quintessence of Presence",description:"UNIQUE: Reduces the cooldown of summoner spells by 4%",rank:"1",effect:"UTILITY",cost:1025},
    {id:5379,tier:3,name:"Greater Quintessence of Momentum",description:"UNIQUE: You regain 75 health and mana whenever you gain a level.",rank:"1",effect:"UTILITY",cost:1025},
    {id:5380,tier:3,name:"Greater Quintessence of Reaping",description:"UNIQUE: Whenever you kill or assist in killing a champion, you gain an additional 12 gold.",rank:"1",effect:"UTILITY",cost:1025},
    {id:8001,tier:2,name:"Mark of the Crippling Candy Cane",description:"+2% critical damage",rank:"1",effect:"PHYSICAL",cost:0},
    {id:8002,tier:1,name:"Lesser Mark of the Yuletide Tannenbaum",description:"+0.62% critical chance",rank:"1",effect:"PHYSICAL",cost:0},
    {id:8003,tier:2,name:"Glyph of the Special Stocking",description:"-0.58% cooldowns",rank:"1",effect:"UTILITY",cost:0},
    {id:8004,tier:2,name:"Seal of the Elusive Snowflake",description:"+0.67% dodge",rank:"1",effect:"UTILITY",cost:0},
    {id:8005,tier:1,name:"Lesser Glyph of the Gracious Gift",description:"+0.12 ability power per level (+2.16 at champion level 18)",rank:"1",effect:"MAGIC",cost:0},
    {id:8006,tier:1,name:"Lesser Seal of the Stout Snowman",description:"+0.72 health per level (+12.96 at champion level 18)",rank:"1",effect:"HEALTH",cost:0},
    {id:8007,tier:1,name:"Lesser Mark of Alpine Alacrity",description:"+1.13% attack speed",rank:"1",effect:"PHYSICAL",cost:0},
    {id:8008,tier:2,name:"Mark of the Combatant",description:"+2% critical damage",rank:"1",effect:"PHYSICAL",cost:0},
    {id:8009,tier:1,name:"Lesser Seal of the Medalist",description:"+3.56 health",rank:"1",effect:"HEALTH",cost:0},
    {id:8010,tier:2,name:"Seal of the Extreme",description:"+0.67% dodge",rank:"1",effect:"UTILITY",cost:0},
    {id:8011,tier:1,name:"Lesser Glyph of the Challenger",description:"+0.66 ability power",rank:"1",effect:"MAGIC",cost:0},
    {id:8012,tier:2,name:"Glyph of the Soaring Slalom",description:"-0.58% cooldowns",rank:"1",effect:"UTILITY",cost:0},
    {id:8013,tier:2,name:"Quintessence of the Headless Horseman",description:"+3.08 armor penetration",rank:"1",effect:"PHYSICAL",cost:495},
    {id:8014,tier:2,name:"Quintessence of the Piercing Screech",description:"+1.75 magic penetration",rank:"1",effect:"MAGIC",cost:495},
    {id:8015,tier:2,name:"Quintessence of Bountiful Treats",description:"+24 health",rank:"1",effect:"HEALTH",cost:995},
    {id:8016,tier:2,name:"Quintessence of the Speedy Specter",description:"+1.39% movement speed",rank:"1",effect:"UTILITY",cost:995},
    {id:8017,tier:2,name:"Quintessence of the Witches Brew",description:"+4.56 ability power",rank:"1",effect:"MAGIC",cost:495},
    {id:8018,tier:2,name:"Quintessence of the Elusive Werewolf",description:"+1.39% dodge",rank:"1",effect:"UTILITY",cost:495},
    {id:8019,tier:3,name:"Greater Quintessence of the Piercing Present",description:"+1.89 magic penetration",rank:"1",effect:"MAGIC",cost:775},
    {id:8020,tier:3,name:"Greater Quintessence of the Deadly Wreath",description:"+3.33 armor penetration",rank:"1",effect:"PHYSICAL",cost:775},
    {id:8021,tier:3,name:"Greater Quintessence of Frosty Fortitude",description:"+26 health",rank:"1",effect:"HEALTH",cost:1550},
    {id:8022,tier:3,name:"Greater Quintessence of Sugar Rush",description:"+1.5% movement speed",rank:"1",effect:"UTILITY",cost:1550},
    {id:8023,tier:3,name:"IntelI3 Quintessence of Fortitude",description:"+26 health",rank:"1",effect:"HEALTH",cost:0},
    {id:8024,tier:3,name:"IntelI7 Mark of Desolation",description:"+1.66 armor penetration",rank:"1",effect:"PHYSICAL",cost:0},
    {id:8025,tier:3,name:"IntelI5 Mark of Insight",description:"+0.95 magic penetration",rank:"1",effect:"MAGIC",cost:0},
    {id:8026,tier:3,name:"IntelI5 Glyph of Force",description:"+0.17 ability power per level (+3.06 at champion level 18)",rank:"1",effect:"MAGIC",cost:0},
    {id:8027,tier:3,name:"IntelI7 Glyph of Focus",description:"-0.65% cooldowns",rank:"1",effect:"UTILITY",cost:0},
    {id:8028,tier:3,name:"IntelI3 Glyph of Warding",description:"+1.49 magic resist",rank:"1",effect:"DEFENSE",cost:0},
    {id:8029,tier:3,name:"IntelI3 Seal of Evasion",description:"+0.75% dodge",rank:"1",effect:"UTILITY",cost:0},
    {id:8030,tier:3,name:"IntelI5 Seal of Clarity",description:"+0.065 mana regen / 5 sec. per level (+1.17 at champion level 18)",rank:"1",effect:"UTILITY",cost:0},
    {id:8031,tier:3,name:"IntelI7 Seal of Resilience",description:"+1.41 armor",rank:"1",effect:"DEFENSE",cost:0},
    {id:8032,tier:3,name:"IntelI3 Mark of Alacrity",description:"+1.7% attack speed",rank:"1",effect:"PHYSICAL",cost:0},
    {id:8033,tier:3,name:"IntelI5 Quintessence of Vigor",description:"+2.7 health regen / 5 sec.",rank:"1",effect:"UTILITY",cost:0},
    {id:8034,tier:3,name:"IntelI7 Quintessence of Malice",description:"+1.86% critical chance",rank:"1",effect:"PHYSICAL",cost:0}
];